import React, { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { 
  Container, 
  Typography, 
  Box, 
  Button, 
  AppBar,
  Toolbar,
  Link,
  Paper,
  Card,
  CardMedia,
  Chip
} from '@mui/material';
import ShareIcon from '@mui/icons-material/Share';
import GetAppIcon from '@mui/icons-material/GetApp';
import LocalCafeIcon from '@mui/icons-material/LocalCafe';
import LightbulbIcon from '@mui/icons-material/Lightbulb';
import CelebrationIcon from '@mui/icons-material/Celebration';
import '../styles/LandingPage.css';
import '../styles/WinnerPage.css';

const WinnerPage = () => {
  const navigate = useNavigate();
  const tripCardRef = useRef(null);
  
  const tripDetails = {
    destination: 'Santorini Getaway',
    dates: 'June 15-22, 2025',
    travelers: '2 Travelers',
    price: '$2,499/person'
  };

  const handleShare = () => {
    navigate('/share');
  };

  const handleDownload = async () => {
    if (tripCardRef.current) {
      try {
        // Create a canvas from the trip card
        const canvas = await html2canvas(tripCardRef.current, {
          scale: 2, // Higher quality
          logging: false,
          useCORS: true // Allow loading cross-origin images
        });

        // Calculate dimensions to fit the PDF
        const imgWidth = 210; // A4 width in mm
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        // Create PDF
        const pdf = new jsPDF('p', 'mm', 'a4');
        
        // Add title
        pdf.setFontSize(24);
        pdf.setTextColor(66, 99, 235); // #4263eb
        pdf.text('Your Trip Details', 105, 20, { align: 'center' });
        
        // Add image
        const imgData = canvas.toDataURL('image/jpeg', 1.0);
        pdf.addImage(imgData, 'JPEG', 0, 30, imgWidth, imgHeight);
        
        // Add footer
        pdf.setFontSize(10);
        pdf.setTextColor(102, 102, 102); // #666666
        pdf.text('Generated by Group Travel AI', 105, 287, { align: 'center' });
        
        // Download PDF
        pdf.save(`${tripDetails.destination.toLowerCase().replace(/\s+/g, '-')}-trip-details.pdf`);
      } catch (error) {
        console.error('Error generating PDF:', error);
        alert('There was an error generating your PDF. Please try again.');
      }
    }
  };

  const handleBuyCoffee = () => {
    navigate('/donate');
  };

  return (
    <div className="landing-page winner-page">
      {/* Confetti animation container - positioned fixed to appear behind content */}
      <div className="confetti-container" style={{ 
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        zIndex: 0,
        pointerEvents: 'none'
      }}>
        {/* Confetti dots will be added via CSS */}
      </div>

      {/* Navigation */}
      <AppBar position="fixed" elevation={0} sx={{ bgcolor: 'background.paper', zIndex: 1100 }}>
        <Toolbar sx={{ justifyContent: 'space-between' }}>
          <Typography 
            variant="h6" 
            component="div" 
            sx={{ 
              color: 'primary.main', 
              fontWeight: 600,
              cursor: 'pointer'
            }}
            onClick={() => navigate('/')}
          >
            Group Travel AI
          </Typography>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 3 }}>
            <Link href="/docs" color="text.secondary" underline="none" sx={{ '&:hover': { color: 'text.primary' } }}>
              Docs
            </Link>
            <Link href="/donate" color="text.secondary" underline="none" sx={{ '&:hover': { color: 'text.primary' } }}>
              Donate
            </Link>
            <Button 
              variant="contained" 
              onClick={() => navigate('/create-trip')}
              className="primary-button"
            >
              Start a Trip
            </Button>
          </Box>
        </Toolbar>
      </AppBar>

      <Container maxWidth="md" sx={{ pt: 12, pb: 8, position: 'relative', zIndex: 1 }}>
        <Box sx={{ display: 'flex', justifyContent: 'center', mb: 4 }}>
          <Chip
            icon={<CelebrationIcon />}
            label="Trip Confirmed!"
            color="primary"
            sx={{ 
              fontSize: '1.1rem', 
              py: 2.5, 
              px: 2,
              "& .MuiChip-icon": { fontSize: '1.5rem' }
            }}
          />
        </Box>

        {/* Trip card */}
        <Card 
          ref={tripCardRef} 
          elevation={3}
          sx={{ 
            borderRadius: 3, 
            overflow: 'hidden',
            mb: 5,
            maxWidth: '700px',
            mx: 'auto',
            position: 'relative',
            zIndex: 1
          }}
        >
          <Box sx={{ position: 'relative' }}>
            <CardMedia
              component="img"
              height="400"
              image="https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800"
              alt="Santorini sunset view with blue domed churches"
              crossOrigin="anonymous"
            />
            <Box
              sx={{
                position: 'absolute',
                bottom: 0,
                left: 0,
                width: '100%',
                bgcolor: 'rgba(0, 0, 0, 0.75)',
                color: 'white',
                padding: 3,
                backdropFilter: 'blur(3px)'
              }}
            >
              <Typography 
                variant="h3" 
                component="h1" 
                gutterBottom 
                sx={{ 
                  color: 'white',
                  textShadow: '1px 1px 3px rgba(0,0,0,0.7)'
                }}
              >
                {tripDetails.destination}
              </Typography>
              <Box sx={{ 
                display: 'flex', 
                flexWrap: 'wrap', 
                gap: 3,
                '& .MuiTypography-root': {
                  fontWeight: 500,
                  textShadow: '1px 1px 2px rgba(0,0,0,0.5)',
                  color: 'white'
                }
              }}>
                <Typography variant="body1">
                  📅 {tripDetails.dates}
                </Typography>
                <Typography variant="body1">
                  👥 {tripDetails.travelers}
                </Typography>
                <Typography variant="body1">
                  💰 {tripDetails.price}
                </Typography>
              </Box>
            </Box>
          </Box>
        </Card>

        {/* What's Next section */}
        <Paper 
          elevation={3} 
          sx={{ 
            p: 4, 
            borderRadius: 3, 
            maxWidth: '700px',
            mx: 'auto',
            position: 'relative',
            zIndex: 1
          }}
        >
          <Typography 
            variant="h4" 
            component="h2" 
            gutterBottom 
            align="center"
            sx={{ mb: 4 }}
          >
            What's Next?
          </Typography>
          
          <Box sx={{ 
            display: 'flex', 
            flexDirection: { xs: 'column', sm: 'row' },
            justifyContent: 'center',
            gap: 2,
            mb: 2
          }}>
            <Button
              variant="outlined"
              startIcon={<ShareIcon />}
              onClick={handleShare}
              fullWidth
              sx={{ py: 1.5 }}
            >
              Share on Socials
            </Button>
            
            <Button
              variant="outlined"
              startIcon={<GetAppIcon />}
              onClick={handleDownload}
              fullWidth
              sx={{ py: 1.5 }}
            >
              Download Trip PDF
            </Button>
            
            <Button
              variant="contained"
              startIcon={<LocalCafeIcon />}
              onClick={handleBuyCoffee}
              className="primary-button"
              fullWidth
              sx={{ py: 1.5 }}
            >
              Buy us a coffee
            </Button>
          </Box>
        </Paper>
      </Container>

      {/* Footer */}
      <footer className="footer" style={{ 
        position: 'relative', 
        zIndex: 1,
        width: '100%',
        marginTop: 'auto',
        left: 0,
        right: 0,
        bottom: 0
      }}>
        <Container maxWidth="lg">
          <div className="footer-content">
            <div className="footer-donate">
              <div className="footer-donate-text">
                <LightbulbIcon />
                <Typography>Keep the API lights on</Typography>
              </div>
              <Button 
                variant="contained"
                onClick={() => navigate('/donate')}
                className="footer-donate-button"
              >
                Donate
              </Button>
            </div>
            <Typography variant="body1" align="center" className="footer-tagline">
              ✈️ Made for group travel lovers
            </Typography>
            <div className="footer-links">
              <Link href="/privacy">Privacy</Link>
              <Link href="/contact">Contact</Link>
            </div>
          </div>
        </Container>
      </footer>
    </div>
  );
};

export default WinnerPage; 